#############################
### ENVIRONMENT VARIABLES ###
#############################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


#################
### AUTOSTART ###
#################

exec-once = nm-applet &
exec-once = waybar
exec-once = awww-daemon &
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store 