# TheOldZoom's Amazing Dotfiles

###################
###  Variables  ###
###################

$terminal = kitty
$fileManager = dolphin
$menu = rofi -show run
$browser = firefox
$discord = vesktop
$musicPlayer = spotify
$editor = code


###############
### Sources ###
###############

$Hl = ~/.config/hypr

source = $Hl/autostart.conf
source = $Hl/monitors.conf
source = $Hl/keybinds.conf
source = $Hl/styles.conf
source = $Hl/input.conf
source = $Hl/windowrules.conf