###################
### KEYBINDINGS ###
###################

$mainMod = SUPER
$scripts = ~/.local/bin

# Core Shortcuts
bind = $mainMod, T, exec, $terminal # Terminal
bind = $mainMod, Q, killactive, # Close Window
bind = $mainMod SHIFT, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit # Power Menu
bind = $mainMod, F, togglefloating, # Toggle Floating
bind = $mainMod, R, exec, $menu # App Launcher
bind = $mainMod, P, pseudo, # Dwindle: Pseudo Tiling
bind = $mainMod, J, togglesplit, # Dwindle: Toggle Split

# Open Applications
bind = $mainMod, E, exec, $fileManager # File Manager
bind = $mainMod, D, exec, $discord # Discord
bind = $mainMod, C, exec, $editor # Text Editor
bind = $mainMod, M, exec, $musicPlayer # Music Player
bind = $mainMod, B, exec, $browser # Web Browser

# Navigation (Focus)
bind = $mainMod, left, movefocus, l # Focus Left
bind = $mainMod, right, movefocus, r # Focus Right
bind = $mainMod, up, movefocus, u # Focus Up
bind = $mainMod, down, movefocus, d # Focus Down

# Workspaces (Switch)
bind = $mainMod, 1, workspace, 1 # Workspace 1
bind = $mainMod, 2, workspace, 2 # Workspace 2
bind = $mainMod, 3, workspace, 3 # Workspace 3
bind = $mainMod, 4, workspace, 4 # Workspace 4
bind = $mainMod, 5, workspace, 5 # Workspace 5
bind = $mainMod, 6, workspace, 6 # Workspace 6
bind = $mainMod, 7, workspace, 7 # Workspace 7
bind = $mainMod, 8, workspace, 8 # Workspace 8
bind = $mainMod, 9, workspace, 9 # Workspace 9
bind = $mainMod, 0, workspace, 10 # Workspace 10

# Workspaces (Move Window)
bind = $mainMod SHIFT, 1, movetoworkspace, 1 # Move to Workspace 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2 # Move to Workspace 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3 # Move to Workspace 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4 # Move to Workspace 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5 # Move to Workspace 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6 # Move to Workspace 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7 # Move to Workspace 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8 # Move to Workspace 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9 # Move to Workspace 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10 # Move to Workspace 10

# Mouse Bindings
bind = $mainMod, mouse_down, workspace, e+1 # Next Workspace
bind = $mainMod, mouse_up, workspace, e-1 # Prev Workspace
bindm = $mainMod, mouse:272, movewindow # Drag Window
bindm = $mainMod, mouse:273, resizewindow # Resize Window

# Media & Brightness
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ # Volume Up
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- # Volume Down
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle # Mute Audio
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle # Mute Mic
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+ # Brightness Up
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%- # Brightness Down

# Media Transport
bindl = , XF86AudioNext, exec, playerctl next # Next Track
bindl = , XF86AudioPause, exec, playerctl play-pause # Play/Pause
bindl = , XF86AudioPlay, exec, playerctl play-pause # Play/Pause
bindl = , XF86AudioPrev, exec, playerctl previous # Previous Track

# Screenshots
bind = $mainMod SHIFT, S, exec, grim -g "$(slurp)" - | swappy -f - # Screenshot Area

# Rofi Menus
bind = $mainMod, A, exec, pkill -x rofi || rofi -show drun # Application Finder
bind = $mainMod, TAB, exec, pkill -x rofi || rofi -show window # Window Switcher
bind = $mainMod Shift, E, exec, pkill -x rofi || rofi -show filebrowser # File Finder
bind = $mainMod, slash, exec, $scripts/keybinds # Keybindings Hint
bind = $mainMod, period, exec, pkill -x rofi || rofi -show emoji # Emoji Picker
bind = $mainMod, W, exec, pkill -x rofi || $scripts/walpick # Wallpaper Picker

# Clipboard
bind = $mainMod, V, exec, pkill -x rofi || $scripts/cliphist # Clipboard History